// <auto-generated />
using System;
using BettingApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BettingApp.Infrastructure.Migrations
{
    [DbContext(typeof(BettingDbContext))]
    [Migration("20260326131502_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BettingApp.Domain.Entities.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BettingMarketId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BettorId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CreditToMoneyRateApplied")
                        .HasPrecision(12, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCommissionFeePaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsWinning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("MarketParticipationMultiplierApplied")
                        .HasPrecision(12, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Odds")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutcomeStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("PlacedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Stake")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("StakeCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StakeRealMoneyEquivalent")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BettingMarketId");

                    b.HasIndex("BettorId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("BettingApp.Domain.Entities.BettingMarket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentOdds")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<decimal>("OpeningOdds")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BettingMarkets");
                });

            modelBuilder.Entity("BettingApp.Domain.Entities.Bettor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Bettors");
                });

            modelBuilder.Entity("BettingApp.Domain.Entities.BettorWallet", b =>
                {
                    b.Property<Guid>("BettorId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LastCreditToMoneyRate")
                        .HasPrecision(12, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LastMoneyToCreditRate")
                        .HasPrecision(12, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("BettorId");

                    b.ToTable("BettorWallets");
                });

            modelBuilder.Entity("BettingApp.Domain.Entities.D3CreditTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BettorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CreditAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CreditToMoneyRate")
                        .HasPrecision(12, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MarketParticipationMultiplier")
                        .HasPrecision(12, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MoneyToCreditRate")
                        .HasPrecision(12, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("RealCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RealMoneyAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BettorId", "CreatedAtUtc");

                    b.ToTable("D3CreditTransactions");
                });

            modelBuilder.Entity("BettingApp.Domain.Entities.Bet", b =>
                {
                    b.HasOne("BettingApp.Domain.Entities.BettingMarket", "BettingMarket")
                        .WithMany("Bets")
                        .HasForeignKey("BettingMarketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BettingApp.Domain.Entities.Bettor", "Bettor")
                        .WithMany("Bets")
                        .HasForeignKey("BettorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BettingMarket");

                    b.Navigation("Bettor");
                });

            modelBuilder.Entity("BettingApp.Domain.Entities.BettorWallet", b =>
                {
                    b.HasOne("BettingApp.Domain.Entities.Bettor", "Bettor")
                        .WithOne("Wallet")
                        .HasForeignKey("BettingApp.Domain.Entities.BettorWallet", "BettorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bettor");
                });

            modelBuilder.Entity("BettingApp.Domain.Entities.D3CreditTransaction", b =>
                {
                    b.HasOne("BettingApp.Domain.Entities.Bettor", "Bettor")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("BettorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bettor");
                });

            modelBuilder.Entity("BettingApp.Domain.Entities.BettingMarket", b =>
                {
                    b.Navigation("Bets");
                });

            modelBuilder.Entity("BettingApp.Domain.Entities.Bettor", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("CreditTransactions");

                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
